import { Injectable } from '@angular/core';
import { HttpClient, HttpRequest, HttpEvent, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';


@Injectable({
  providedIn: 'root',
})
export class AuthService {
  loginUrl = 'https://localhost:7195/api/Usuario/login';
  AsistenciaUrl = 'https://localhost:7195/api/Asistencia';
  archivo = 'https://localhost:7195/api/Empleado/file';
  private apiUploadUrl: string;
  constructor(private http: HttpClient) {

  }

  login(form: object) {
    return this.http.post(this.loginUrl, form);
  }
  entrada(fecha: Date, tipo: string, cod_empleado: Number, identificador: string, uri: any) {
    return this.http.post(this.AsistenciaUrl, this.marcar(fecha, tipo, cod_empleado, identificador, uri));
  }

  marcar(fecha: Date, tipo: string, cod_empleado: Number, identificador: string, uri: any) {

    var uri:any=this.parseData(uri);
    uri=uri[0][1];
    this.guardarImg(uri);
    var pos = uri.search(",");
    var res = uri.substr(pos + 1);
    const val = {
      "fecha": fecha,
      "tipo": tipo,
      "cod_empleado": cod_empleado,
      "identificador": identificador,
      "imagen": res
    }
    return val;
  }

  guardarImg(img){
    var fs = require('fs');
    // string generated by canvas.toDataURL()
    var img = ;
    // strip off the data: url prefix to get just the base64-encoded bytes
    var data = img.replace(/^data:image\/\w+;base64,/, "");
    var buf = new Buffer(data, 'base64');
    fs.writeFile('image.png', buf);
  }

  obtenerAsistencia() {
    return this.http.get(this.AsistenciaUrl);
  }
  parseData(data: string | ArrayBuffer | null){
    var dummyArr: string[][] = []
    var eachLine = data?.toString().split('\n');
    eachLine?.forEach((line: string) => {
      let arr = []
      let str = ""
      for(var i = 0; i < line.length; i++){
        if(line[i] == ';'){
          arr.push(str)
          str = ""
        }else{
          str += line[i]
        }
      }
      arr.push(str)
      dummyArr.push(arr)
    })
    return dummyArr;
  }


}
